apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  namespace: default
  labels:
      release: prometheus
spec:
  selector:
    matchLabels:
      app: app-service
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
